# Generated by Django 4.2.23 on 2025-06-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_auto_20240829_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='post',
        ),
    ]
