<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-06-11 09:57
=======
# Generated by Django 4.2.23 on 2025-06-11 10:08
>>>>>>> 7fcf98190ac606f5a83a7d3aa733b6b1d40922f5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_auto_20240829_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='post',
        ),
    ]
